#!/bin/sh

#Allow the current user to change the backlight level.

if [[ $EUID -ne 0 ]]; then
  echo "You must run this with superuser privileges." 2>&1
  exit 1
fi

echo 'ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"' > /etc/udev/rules.d/backlight.rules || exit
echo '/etc/udev/rules.d/backlight.rules added'

usermod -a -G video $SUDO_USER || exit
echo 'user added to group video'

