#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "You must run this with superuser privileges." 2>&1
  exit 1
fi

sudo systemctl disable onetimelogin.service
sudo rm -f /etc/systemd/system/onetimelogin.service /etc/systemd/system/getty@tty1.service.d/autologin.conf /bin/autologin.sh
