#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "You must run this with superuser privileges." 2>&1
  exit 1
fi

sudo pacman --noconfirm -S dkms linux-headers
sudo -u "$SUDO_USER" yay -S --noconfirm rtl8821ce-dkms-git;
sudo tee /etc/modprobe.d/ideapad.conf <<< "blacklist ideapad_laptop";

sudo echo 'Section "InputClass"
   Identifier "libinput touchpad catchall"
   MatchIsTouchpad "on"
   MatchDevicePath "/dev/input/event*"
   Driver "synaptic"
   Option "ClickMethod" "clickfinger"

   #click on tap
   Option "TapButton1" "1"
   Option "MaxTapTime" "100"

   #disable acceleration
   Option "AccelerationProfile" "-1"
   Option "AccelerationScheme" "none"
   Option "AccelSpeed" "-1"
EndSection
' > /usr/share/X11/xorg.conf.d/52-elantech-touchpad.conf;
