#!/bin/sh

if [[ $EUID -ne 0 ]]; then
  echo "You must run this with superuser privileges." 2>&1
  exit 1
fi

fallocate -l 8192M /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile

echo "# swap
/swapfile none swap default 0 0" >> /etc/fstab
