#!/bin/sh
alias p="sudo pacman" \
	sv="sudo systemctl" \
	rrm="/bin/rm" \
	rm="trash" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
    nnn="nnn -e"

#on vérifie que nvim est installé et on remplce vim par nvim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
